
/* eslint-disable @next/next/no-page-custom-font */
/* eslint-disable @next/next/google-font-display */
import Script from 'next/script';
import type { Metadata } from "next";
import { Inter } from "next/font/google";


import '../../public/assets/css/main.css'; // global css
import '../../public/assets/vendor/bootstrap/css/bootstrap.min.css';
import '../../public/assets/vendor/bootstrap-icons/bootstrap-icons.css';
import '../../public/assets/vendor/glightbox/css/glightbox.min.css';
import '../../public/assets/vendor/swiper/swiper-bundle.min.css';
import '../../public/assets/vendor/aos/aos.css'; // import AOS CSS


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <head>
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Roboto:100,300,400,500,700|Philosopher:400,400i,700,700i' rel='stylesheet' />
      </head>
      <body>
        
        {children}
        
        <Script src="assets/js/main.js" />
        <Script src="assets/vendor/aos/aos.js" />
        <Script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js" />
        <Script src="assets/vendor/glightbox/js/glightbox.min.js" />
        <Script src="assets/vendor/swiper/swiper-bundle.min.js" />
      </body>
    </html>
  )
}
